baseURL = 'https://example.org/'
languageCode = 'nl'
title = 'Developer Portfolio: Paulo Deen'

[[menus.main]]
name = 'Projecten'
pageRef = '/projecten'
weight = 10

[[menus.main]]
name = 'Pragmatische Boekenplank 2024'
pageRef = '/boekenplank'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
